[package]
name = "deskpuck-ble"
description = "Bluetooth LE connection to a Joy-Con 2 for Deskpuck"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
deskpuck-core = { path = "../deskpuck-core" }
deskpuck-inject = { path = "../deskpuck-inject" }
