[workspace]
resolver = "3"
members = ["deskpuck-ble", "deskpuck-core", "deskpuck-inject", "deskpuck-replay"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
